# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{empp}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["lijianjun"]
  s.date = %q{2011-01-21}
  s.description = %q{API for sending or receiving sms}
  s.email = %q{jjli418@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README",
    "README.rdoc"
  ]
  s.files = [
    "lib/empp.rb",
    "lib/empp/constants.rb",
    "lib/empp/delivery_state.rb",
    "lib/empp/empp.rb",
    "lib/empp/empp_base.rb",
    "lib/empp/empp_connection.rb",
    "lib/empp/empp_logger.rb",
    "lib/empp/empp_msg_listener.rb",
    "lib/empp/empp_parser.rb",
    "lib/empp/empp_result_listener.rb",
    "lib/empp/msg_active_test.rb",
    "lib/empp/msg_active_test_resp.rb",
    "lib/empp/msg_connect.rb",
    "lib/empp/msg_connect_resp.rb",
    "lib/empp/msg_delivery.rb",
    "lib/empp/msg_delivery_resp.rb",
    "lib/empp/msg_submit.rb",
    "lib/empp/msg_submit_resp.rb",
    "lib/empp/tcp_connection.rb",
    "lib/empp/utils/bytebuffer.rb",
    "lib/empp/utils/hashtable.rb",
    "lib/empp/utils/utils.rb"
  ]
  s.homepage = %q{http://github.com/temptest/empp}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{API for sending or receiving sms}
  s.test_files = [
    "test/helper.rb",
    "test/test_empp.rb",
    "test/test_msg_submit.rb",
    "test/test_tcp_connection.rb",
    "test/test_utils.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_runtime_dependency(%q<bindata>, ["= 1.2.1"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<bindata>, ["= 1.2.1"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<bindata>, ["= 1.2.1"])
  end
end

